language: php

php:
  - 7.0
  - hhvm

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update
  - composer update $COMPOSER_OPTS

script:
  - ./vendor/bin/phpunit
  - ./tests/lint.sh

git:
  depth: 5
